version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: imagery-processing_zookeeper_1
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: imagery-processing_kafka_1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181